/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20Mintable } from "./ERC20Mintable";
export type { IStakingRegistry } from "./IStakingRegistry";
export type { RollStakingFactoryV2 } from "./RollStakingFactoryV2";
export type { RollStakingRewardsV2 } from "./RollStakingRewardsV2";
export type { StakingRegistry } from "./StakingRegistry";

export { ERC20Mintable__factory } from "./factories/ERC20Mintable__factory";
export { IStakingRegistry__factory } from "./factories/IStakingRegistry__factory";
export { RollStakingFactoryV2__factory } from "./factories/RollStakingFactoryV2__factory";
export { RollStakingRewardsV2__factory } from "./factories/RollStakingRewardsV2__factory";
export { StakingRegistry__factory } from "./factories/StakingRegistry__factory";
